version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: MiniiPaaS.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=MiniIPaaS;User=root;Password=Password123!;
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080  # React'in API'ye erişimi için
    depends_on:
      - api
    stdin_open: true  # Hot reload için gerekli
    tty: true        # React dev server için

  worker:
    build:
      context: .
      dockerfile: MiniiPaaS.Worker/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: MiniIPaaS
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  mysql_data: